=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cameraConfigurationFile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="viewCapabilities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="ptzType" type="xs:string" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nil"/>
                                        <xs:enumeration value="P"/>
                                        <xs:enumeration value="T"/>
                                        <xs:enumeration value="Z"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ptzControl" type="xs:string" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="CONT"/>
                                        <xs:enumeration value="ABS"/>
                                        <xs:enumeration value="REL"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="viewAngle" type="xs:unsignedByte" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:maxInclusive value="360"/>
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="isPTZ" type="xs:boolean" use="required" />
                        <xs:attribute name="maxPanViewAngle" type="xs:decimal" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:maxInclusive value="180"/>
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="minPanViewAngle" type="xs:decimal" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="-180"/>
                                    <xs:maxInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="maxTiltViewAngle" type="xs:decimal" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:maxInclusive value="180"/>
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="minTiltViewAngle" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="-180"/>
                                    <xs:maxInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="maxZoom" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="minZoom" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cameraOrientation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="globalVector">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bearing">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxExclusive value="360"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="roll" type="xs:decimal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxExclusive value="360"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="pitch" type="xs:decimal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minExclusive value="-90"/>
                                                    <xs:maxExclusive value="90"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="location">
                    <xs:complexType>
                        <xs:attribute name="hasCoordinates" type="xs:boolean" use="required" />
                        <xs:attribute name="height2Ground" use="required" >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minExclusive value="-90"/>
                                    <xs:maxExclusive value="90"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="latitude" use="required"  >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="-90"/>
                                    <xs:maxInclusive value="90"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="longitude" use="required"  >
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minExclusive value="-180"/>
                                    <xs:maxExclusive value="180"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="additionalAttributes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="entry">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="string" type="xs:string" />
                                        <xs:element minOccurs="0" name="double" type="xs:decimal" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="cameraDesignStandard" type="xs:string" use="required" />
            <xs:attribute name="id" type="xs:string" use="required" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="url" type="xs:string" use="required" />
            <xs:attribute name="streamURI" type="xs:string" use="required" />
            <xs:attribute name="username" type="xs:string" use="required" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="password" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_time2_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cameraDesignStandard>ONVIF</cameraDesignStandard>
  <id>3682328865</id>
  <url>http://192.168.1.79:10080/onvif_device</url>
  <username>admin</username>
  <password></password>
  <viewCapabilities isPTZ="true">
    <ptzType>P</ptzType>
    <ptzType>T</ptzType>
    <ptzControl>CONT</ptzControl>
    <viewAngle>62</viewAngle>
    <maxPanViewAngle>147.5</maxPanViewAngle>
    <minPanViewAngle>-147.5</minPanViewAngle>
    <maxTiltViewAngle>45.0</maxTiltViewAngle>
    <minTiltViewAngle>-45.0</minTiltViewAngle>
    <maxZoom>0.0</maxZoom>
    <minZoom>0.0</minZoom>
  </viewCapabilities>
  <cameraOrientation>
      <bearing>45</bearing>
      <roll>0.0</roll>
      <pitch>0.0</pitch>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947579" longitude="-1.042411" coordinateSys="OUTDOOR"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string>rtsp</string>
    </entry>
    <entry>
      <string>range</string>
      <double>50.0</double>
    </entry>
    <entry>
      <string>resolution</string>
      <string>720</string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string>10554/tcp/av0_0</string>
    </entry>
    <entry>
      <string>pairedCamera</string>
      <string>305419896</string>
    </entry>
    <entry>
      <string>pairedCameraPosition</string>
      <string>right</string>
    </entry>
    <entry>
      <string>pairedCameraData</string>
      <string>1</string>
    </entry>
    <entry>
      <string>panCalibValue</string>
      <string>15</string>
    </entry>
    <entry>
      <string>tiltCalibValue</string>
      <string>0.7</string>
    </entry>
    <entry>
      <string>mapFeature_Road</string>
      <platform.map.SimpleMapConfig>
        <swLong>-1.042411</swLong>
        <swLat>53.947579</swLat>
        <neLong>-1.042111</neLong>
        <neLat>53.947879</neLat>
        <coordinateSys>OUTDOOR</coordinateSys>
      </platform.map.SimpleMapConfig>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>

=== TasMarshall/mcpPlatform/src/main/resources/testFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" cameraDesignStandard="ONVIF" id="3682328865" url="http://192.168.1.75:10080/onvif_device" streamURI="rtsp://192.168.1.75:10554/tcp/av0_0" username="admin" password="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<viewCapabilities viewAngle="62" isPTZ="true" maxPanViewAngle="147.5" minPanViewAngle="-147.5" maxTiltViewAngle="45.0" minTiltViewAngle="-45.0" maxZoom="0.0" minZoom="0.0">
    <ptzType>P</ptzType>
    <ptzType>T</ptzType>
    <ptzControl>CONT</ptzControl>
  </viewCapabilities>
  <cameraOrientation>
    <globalVector>
      <bearing>45</bearing>
      <roll>0.0</roll>
      <pitch>0.0</pitch>
    </globalVector>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947579" longitude="-1.042411"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string>rtsp</string>
    </entry>
    <entry>
      <string>range</string>
      <double>50.0</double>
    </entry>
    <entry>
      <string>resolution</string>
      <string>720</string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string>10554/tcp/av0_0</string>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>

=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_dahua_ptz.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cameraDesignStandard>ONVIF</cameraDesignStandard>
  <id>dahua_ptz</id>
  <url>http://192.168.1.109/onvif_device</url>
  <username>admin</username>
  <password>softwareplatform2018</password>
  <viewCapabilities isPTZ="true">
    <ptzType>P</ptzType>
    <ptzType>T</ptzType>
    <ptzType>Z</ptzType>
    <ptzControl>CONT</ptzControl>
    <viewAngle>62</viewAngle>
    <maxPanViewAngle>147.5</maxPanViewAngle>
    <minPanViewAngle>-147.5</minPanViewAngle>
    <maxTiltViewAngle>45.0</maxTiltViewAngle>
    <minTiltViewAngle>-45.0</minTiltViewAngle>
    <maxZoom>4.0</maxZoom>
    <minZoom>0.0</minZoom>
  </viewCapabilities>
  <cameraOrientation>
      <bearing>45</bearing>
      <roll>180.0</roll>
      <pitch>0.0</pitch>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947579" longitude="-1.042411" coordinateSys="OUTDOOR"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string>rtsp</string>
    </entry>
    <entry>
      <string>range</string>
      <double>50.0</double>
    </entry>
    <entry>
      <string>resolution</string>
      <string>720</string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string>10554/tcp/av0_0</string>
    </entry>
    <entry>
      <string>pan2Entry</string>
      <string>0</string>
    </entry>
    <entry>
      <string>tilt2Entry</string>
      <string>0</string>
    </entry>
    <entry>
      <string>EntryDirection</string>
      <string>right</string>
    </entry>
    <entry>
      <string>panCalibValue</string>
      <string>10.2</string>
    </entry>
    <entry>
      <string>tiltCalibValue</string>
      <string>2.5</string>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>

=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_dahua_fixed.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cameraDesignStandard>ONVIF</cameraDesignStandard>
  <id>dahua_fixed</id>
  <url>http://192.168.1.108/onvif_device</url>
  <username>admin</username>
  <password>softwareplatform2018</password>
  <viewCapabilities isPTZ="false">
    <ptzType>Nil</ptzType>
    <ptzControl>CONT</ptzControl>
    <viewAngle>62</viewAngle>
  </viewCapabilities>
  <cameraOrientation>
      <bearing>45</bearing>
      <roll>180</roll>
      <pitch>0.0</pitch>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947579" longitude="-1.042411" coordinateSys="INDOOR"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string>rtsp</string>
    </entry>
    <entry>
      <string>range</string>
      <string>50.0</string>
    </entry>
    <entry>
      <string>resolution</string>
      <string>720</string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string>10554/tcp/av0_0</string>
    </entry>
    <entry>
      <string>pairedCamera</string>
      <string>305419896</string>
    </entry>
    <entry>
      <string>pairedCameraPosition</string>
      <string>right</string>
    </entry>
    <entry>
      <string>pairedCameraData</string>
      <string>1</string>
    </entry>
    <entry>
      <string>panCalibValue</string>
      <string>9</string>
    </entry>
    <entry>
      <string>tiltCalibValue</string>
      <string>1</string>
    </entry>
    <entry>
      <string>mapFeature_Road</string>
      <platform.map.SimpleMapConfig>
        <swLong>-2</swLong>
        <swLat>53</swLat>
        <neLong>0</neLong>
        <neLat>54</neLat>
        <coordinateSys>OUTDOOR</coordinateSys>
      </platform.map.SimpleMapConfig>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>

=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_sim1.xml
<?xml version="1.0" encoding="UTF-8"?>

<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" id="744f10b7-d9ea-4021-9e1d-a3b04221b2ac" url="000.000.0.00:0" username="admin" password="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" streamURI="" cameraDesignStandard="SIM">
  <viewCapabilities viewAngle="62" isPTZ="true" maxPanViewAngle="147.5" minPanViewAngle="-147.5" maxTiltViewAngle="45.0" minTiltViewAngle="-45.0" maxZoom="0.0" minZoom="0.0">
    <ptzType>P</ptzType>
    <ptzType>T</ptzType>
    <ptzControl>CONT</ptzControl>
  </viewCapabilities>
  <cameraOrientation>
    <globalVector>
      <bearing>0.0</bearing>
      <roll>0.0</roll>
      <pitch>0.0</pitch>
    </globalVector>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947503" longitude="-1.042712"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string></string>
    </entry>
    <entry>
      <string>range</string>
      <double>50.0</double>
    </entry>
    <entry>
      <string>resolution</string>
      <string></string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string></string>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>

=== TasMarshall/mcpPlatform/src/main/resources/camera_configuration_onvif1.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameraConfigurationFile xsi:noNamespaceSchemaLocation="camera_configuration_schema.xsd" cameraDesignStandard="ONVIF" id="3682328865" url="http://192.168.1.77:10080/onvif_device" username="admin" password="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<viewCapabilities viewAngle="62" isPTZ="true" maxPanViewAngle="147.5" minPanViewAngle="-147.5" maxTiltViewAngle="45.0" minTiltViewAngle="-45.0" maxZoom="0.0" minZoom="0.0">
    <ptzType>P</ptzType>
    <ptzType>T</ptzType>
    <ptzControl>CONT</ptzControl>
  </viewCapabilities>
  <cameraOrientation>
    <globalVector>
      <bearing>45</bearing>
      <roll>0.0</roll>
      <pitch>0.0</pitch>
    </globalVector>
  </cameraOrientation>
  <location hasCoordinates="true" height2Ground="10.0" latitude="53.947579" longitude="-1.042411" coordinateSys="OUTDOOR"/>
  <additionalAttributes>
    <entry>
      <string>streamProt</string>
      <string>rtsp</string>
    </entry>
    <entry>
      <string>range</string>
      <double>50.0</double>
    </entry>
    <entry>
      <string>resolution</string>
      <string>720</string>
    </entry>
    <entry>
      <string>streamExt</string>
      <string>10554/tcp/av0_0</string>
    </entry>
    <entry>
      <string>pairedCamera</string>
      <string>2</string>
    </entry>
    <entry>
      <string>pairedCameraPosition</string>
      <string>left</string>
    </entry>
    <entry>
      <string>pairedCameraData</string>
      <string>2</string>
    </entry>
    <entry>
      <string>panCalibValue</string>
      <string>8</string>
    </entry>
    <entry>
      <string>mapFeature_Road</string>
      <platform.core.map.SimpleMapConfig>
        <swLong>-1.042411</swLong>
        <swLat>53.947579</swLat>
        <neLong>-1.042111</neLong>
        <neLat>53.947879</neLat>
        <coordinateSys>OUTDOOR</coordinateSys>
      </platform.core.map.SimpleMapConfig>
    </entry>
  </additionalAttributes>
</cameraConfigurationFile>
