=== TasMarshall/mcpPlatform/src/main/resources/mca_configuration_schema.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="multiCameraCore__configuration__file">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cameraConfigurationFiles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="string" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="multiCameraGoals">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="multiCameraGoal" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:boolean" name="activated" minOccurs="1"/>
                                        <xs:element type="xs:string" name="goalType" minOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="NORMAL"/>
                                                    <xs:enumeration value="CALIBRATION"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="cameraRequirements" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:boolean" name="working" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="inRange" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="motionAvailable" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="motionNotAvailable" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="pan" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="tilt" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="zoom" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="specificID" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="exclusive" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="calibrated" minOccurs="1"/>
                                                    <xs:element type="xs:boolean" name="specificIDs">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="string" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="calibrationIDs">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="string" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="nonMotionBehaviors">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="motionControllerType"/>
                                        <xs:element name="visualObservationsOfInterest">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="visualObservationOfInterest" maxOccurs="unbounded" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="id"/>
                                                                <xs:element name="analysisAlgorithm">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="additionalAttr">
                                                                                <xs:complexType mixed="true">
                                                                                    <xs:sequence>
                                                                                        <xs:element name="attr" maxOccurs="unbounded" minOccurs="0">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element type="xs:string" name="description"/>
                                                                                                    <xs:element name="value">
                                                                                                        <xs:complexType>
                                                                                                            <xs:simpleContent>
                                                                                                                <xs:extension base="xs:short">
                                                                                                                    <xs:attribute type="xs:string" name="class" use="required"/>
                                                                                                                </xs:extension>
                                                                                                            </xs:simpleContent>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute type="xs:string" name="imageAnalysisType" use="required"/>
                                                                        <xs:attribute type="xs:integer" name="precedence" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="map">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:float" name="swLong">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:decimal">
                                                                <xs:minExclusive value="-180"/>
                                                                <xs:maxExclusive value="180"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:float" name="swLat">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:decimal">
                                                                <xs:minInclusive value="-90"/>
                                                                <xs:maxInclusive value="90"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:float" name="neLong">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:decimal">
                                                                <xs:minExclusive value="-180"/>
                                                                <xs:maxExclusive value="180"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:float" name="neLat">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:decimal">
                                                                <xs:minInclusive value="-90"/>
                                                                <xs:maxInclusive value="90"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="class" use="required"/>
                                                <xs:attribute type="xs:string" name="coordinateSys" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="OUTDOOR"/>
                                                            <xs:enumeration value="INDOOR"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute type="xs:string" name="mapType" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="GLOBAL"/>
                                                            <xs:enumeration value="LOCAL"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="additionalFieldMap" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded" name="entry" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element maxOccurs="2" name="string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                    <xs:attribute type="xs:byte" name="priority" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="analysisTypeManager">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="stringToAnalysisMap">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="attr" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="description"/>
                                                    <xs:element name="value">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="class" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="adaptationTypeManager">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="stringToAdaptationMap">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="attr" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="description"/>
                                                    <xs:element name="value">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="class" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="additionalFields">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entry" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element name="value"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TasMarshall/mcpPlatform/src/main/resources/proofOfConceptApp2.xml
<?xml version="1.0" encoding="UTF-8"?>

<multiCameraCore__configuration__file id="proofOfConceptApplication_Two"
                                      xsi:noNamespaceSchemaLocation="mca_configuration_schema.xsd"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <cameraConfigurationFiles>
        <string>camera_configuration_time2_1_app2</string>
        <string>camera_configuration_time2_2_app2</string>
        <string>camera_configuration_dahua_fixed</string>
    </cameraConfigurationFiles>
    <multiCameraGoals>
        <multiCameraGoal id="monitorInterior" priority="5">
            <activated>true</activated>
            <goalType>NORMAL</goalType>
            <cameraRequirements>
                <working>true</working>
                <inRange>true</inRange>
                <motionAvailable>false</motionAvailable>
                <motionNotAvailable>true</motionNotAvailable>
                <pan>false</pan>
                <tilt>false</tilt>
                <zoom>false</zoom>
                <specificID>false</specificID>
                <exclusive>false</exclusive>
                <calibrated>false</calibrated>
                <specificIDs/>
                <calibrationIDs/>
            </cameraRequirements>
            <nonMotionBehaviors>
                <string>ACTIVATE_ALARM</string>
            </nonMotionBehaviors>
            <motionControllerType/>
            <visualObservationsOfInterest>
                <visualObservationOfInterest>
                    <id>intersections</id>
                    <analysisAlgorithm imageAnalysisType="RED_OBJ_LOCATOR" precedence="2">
                        <additionalAttr/>
                    </analysisAlgorithm>
                </visualObservationOfInterest>
            </visualObservationsOfInterest>
            <map class="localMap" coordinateSys="INDOOR" mapType="LOCAL">
                <swLong>-2</swLong>
                <swLat>53</swLat>
                <neLong>0</neLong>
                <neLat>54</neLat>
            </map>
            <additionalFieldMap/>
        </multiCameraGoal>
        <multiCameraGoal id="monitorIntersection" priority="9">
            <activated>true</activated>
            <goalType>NORMAL</goalType>
            <cameraRequirements>
                <working>true</working>
                <inRange>true</inRange>
                <motionAvailable>true</motionAvailable>
                <motionNotAvailable>true</motionNotAvailable>
                <pan>false</pan>
                <tilt>false</tilt>
                <zoom>false</zoom>
                <specificID>false</specificID>
                <exclusive>false</exclusive>
                <calibrated>true</calibrated>
                <specificIDs/>
                <calibrationIDs>
                    <string>findIntersection</string>
                </calibrationIDs>
            </cameraRequirements>
            <nonMotionBehaviors/>
            <motionControllerType>FOCUS_INTERSECT</motionControllerType>
            <visualObservationsOfInterest>
                <visualObservationOfInterest>
                    <id>asdf</id>
                    <analysisAlgorithm imageAnalysisType="GREEN_OBJ_LOCATOR" precedence="2">
                        <additionalAttr/>
                    </analysisAlgorithm>
                </visualObservationOfInterest>
            </visualObservationsOfInterest>
            <map class="globalMap" coordinateSys="OUTDOOR" mapType="GLOBAL">
                <swLong>-2</swLong>
                <swLat>53</swLat>
                <neLong>0</neLong>
                <neLat>54</neLat>
            </map>
            <additionalFieldMap/>
        </multiCameraGoal>
        <multiCameraGoal id="monitorEntry" priority="5">
            <activated>false</activated>
            <goalType>NORMAL</goalType>
            <cameraRequirements>
                <working>true</working>
                <inRange>true</inRange>
                <motionAvailable>true</motionAvailable>
                <motionNotAvailable>false</motionNotAvailable>
                <pan>false</pan>
                <tilt>false</tilt>
                <zoom>false</zoom>
                <specificID>false</specificID>
                <exclusive>true</exclusive>
                <calibrated>true</calibrated>
                <specificIDs/>
                <calibrationIDs>findIntersection</calibrationIDs>
            </cameraRequirements>
            <nonMotionBehaviors>
                <string>DETECT_LOST_RED</string>
            </nonMotionBehaviors>
            <motionControllerType>OBSERVE_ENTRY</motionControllerType>
            <visualObservationsOfInterest>
                <visualObservationOfInterest>
                    <id>alarmObject</id>
                    <analysisAlgorithm imageAnalysisType="RED_OBJ_LOCATOR" precedence="2">
                        <additionalAttr/>
                    </analysisAlgorithm>
                </visualObservationOfInterest>
                <visualObservationOfInterest>
                    <id>entrys</id>
                    <analysisAlgorithm imageAnalysisType="WHITE_OBJ_LOCATOR" precedence="3">
                        <additionalAttr>
                            <attr>
                                <description>NUMBER_OBJECTS</description>
                                <value class="int">1</value>
                            </attr>
                        </additionalAttr>
                    </analysisAlgorithm>
                </visualObservationOfInterest>
            </visualObservationsOfInterest>
            <map class="globalMap" coordinateSys="OUTDOOR" mapType="GLOBAL">
                <swLong>-2</swLong>
                <swLat>53</swLat>
                <neLong>0</neLong>
                <neLat>54</neLat>
            </map>
            <additionalFieldMap/>
        </multiCameraGoal>
        <multiCameraGoal id="findIntersection" priority="10">
            <activated>true</activated>
            <goalType>CALIBRATION</goalType>
            <cameraRequirements>
                <working>true</working>
                <inRange>true</inRange>
                <motionAvailable>true</motionAvailable>
                <motionNotAvailable>false</motionNotAvailable>
                <pan>false</pan>
                <tilt>false</tilt>
                <zoom>false</zoom>
                <specificID>false</specificID>
                <exclusive>false</exclusive>
                <calibrated>false</calibrated>
                <specificIDs/>
                <calibrationIDs/>
            </cameraRequirements>
            <nonMotionBehaviors/>
            <motionControllerType>CALIBRATED_POSITIONER</motionControllerType>
            <visualObservationsOfInterest>
                <visualObservationOfInterest>
                    <id>imageComparison</id>
                    <analysisAlgorithm imageAnalysisType="IMAGE_COMPARATOR" precedence="1">
                        <additionalAttr/>
                    </analysisAlgorithm>
                </visualObservationOfInterest>
            </visualObservationsOfInterest>
            <map class="globalMap" coordinateSys="OUTDOOR" mapType="GLOBAL">
                <swLong>-2</swLong>
                <swLat>53</swLat>
                <neLong>0</neLong>
                <neLat>54</neLat>
            </map>
            <additionalFieldMap/>
        </multiCameraGoal>
    </multiCameraGoals>
    <analysisTypeManager>
        <stringToAnalysisMap>
            <attr>
                <description>IMAGE_COMPARATOR</description>
                <value class="platform.imageAnalysis.impl.ImageComparator"/>
            </attr>
            <attr>
                <description>GREEN_OBJ_LOCATOR</description>
                <value class="platform.imageAnalysis.impl.GreenObjectLocator"/>
            </attr>
            <attr>
                <description>RED_OBJ_LOCATOR</description>
                <value class="platform.imageAnalysis.impl.RedObjectLocator"/>
            </attr>
            <attr>
                <description>BLUE_OBJ_LOCATOR</description>
                <value class="platform.imageAnalysis.impl.BlueObjectLocator"/>
            </attr>
            <attr>
                <description>WHITE_OBJ_LOCATOR</description>
                <value class="platform.imageAnalysis.impl.WhiteObjectLocator"/>
            </attr>
        </stringToAnalysisMap>
    </analysisTypeManager>
    <adaptationTypeManager>
        <stringToAdaptationMap>
            <attr>
                <description>CALIBRATED_POSITIONER</description>
                <value class="platform.behaviors.impl.CalibratedScanForObject"/>
            </attr>
            <attr>
                <description>FOCUS_INTERSECT</description>
                <value class="platform.behaviors.impl.ObjectToCentre"/>
            </attr>
            <attr>
                <description>ACTIVATE_ALARM</description>
                <value class="platform.behaviors.impl.ActivateAlarm"/>
            </attr>
            <attr>
                <description>DETECT_LOST_RED</description>
                <value class="platform.behaviors.impl.DetectLostRedObject"/>
            </attr>
            <attr>
                <description>OBSERVE_ENTRY</description>
                <value class="platform.behaviors.impl.ObserveEntry"/>
            </attr>
        </stringToAdaptationMap>
    </adaptationTypeManager>
    <additionalFields>
        <entry>
            <description>heartbeat</description>
            <value>30000</value>
        </entry>
        <entry>
            <description>executionTimeTesting</description>
            <value>0a</value>
        </entry>
        <entry>
            <description>testMode</description>
            <value>0</value>
        </entry>
    </additionalFields>
</multiCameraCore__configuration__file>
